
export const cssQuestions = [
  { question: "CSS stand for?", options: ["Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], answer: 1 },
  { question: "Which HTML attribute is used to define inline styles?", options: ["class", "font", "styles", "style"], answer: 3 },
  { question: "Which CSS property controls the text size?", options: ["font-style", "text-size", "font-size", "text-style"], answer: 2 },
  { question: "How do you insert a comment in a CSS file?", options: ["// this is a comment //", "/* this is a comment */", "' this is a comment", "<!-- this is a comment -->"], answer: 1 },
  { question: "Which property is used to change the background color?", options: ["color", "bgcolor", "background-color", "bg-color"], answer: 2 },
  { question: "How do you add a background image?", options: ["background-image: url('image.jpg')", "bg-image: url('image.jpg')", "background: image('image.jpg')", "image: background('image.jpg')"], answer: 0 },
  { question: "Which CSS property controls text color?", options: ["text-color", "color", "font-color", "text-style"], answer: 1 },
  { question: "Which property is used to change the font of an element?", options: ["font-family", "font-style", "font-weight", "text-font"], answer: 0 },
  { question: "How do you make text bold?", options: ["font: bold", "style: bold", "font-weight: bold", "text-style: bold"], answer: 2 },
  { question: "How do you make text italic?", options: ["font-style: italic", "style: italic", "font: italic", "text-style: italic"], answer: 0 },
  { question: "How do you display a border around an element?", options: ["border-style: solid", "border-line: solid", "border-width: solid", "border: solid"], answer: 3 },
  { question: "Which property is used to change the left margin of an element?", options: ["padding-left", "margin-left", "indent", "left-margin"], answer: 1 },
  { question: "How do you make a list display horizontally?", options: ["list-style: horizontal", "list-type: inline", "display: inline", "list-direction: horizontal"], answer: 2 },
  { question: "Which property is used to change the inside spacing of an element?", options: ["margin", "spacing", "padding", "inside-margin"], answer: 2 },
  { question: "How do you select an element with id 'demo'?", options: [".demo", "#demo", "*demo", "demo"], answer: 1 },
  { question: "How do you select elements with class 'test'?", options: ["*test", "#test", ".test", "test"], answer: 2 },
  { question: "How do you select all p elements inside a div element?", options: ["div.p", "div + p", "div p", "div > p"], answer: 2 },
  { question: "What is the default value of the position property?", options: ["fixed", "relative", "absolute", "static"], answer: 3 },
  { question: "How do you make an element stick to the viewport?", options: ["position: fixed", "position: sticky", "position: static", "position: relative"], answer: 0 },
  { question: "Which property is used to create rounded corners?", options: ["border-radius", "corner-radius", "rounded-corners", "border-curve"], answer: 0 },
  { question: "Which property is used to add shadow to elements?", options: ["shadow", "box-shadow", "element-shadow", "drop-shadow"], answer: 1 },
  { question: "How do you make a flex container?", options: ["display: flexbox", "display: flex", "display: inline-flex", "display: block-flex"], answer: 1 },
  { question: "Which property aligns flex items vertically in a flex container?", options: ["align-content", "justify-content", "align-items", "flex-align"], answer: 2 },
  { question: "Which property changes the order of flex items?", options: ["order", "flex-order", "item-order", "flex-direction"], answer: 0 },
  { question: "How do you create a grid layout?", options: ["display: block-grid", "display: grid", "display: inline-grid", "display: flex-grid"], answer: 1 },
  { question: "Which property defines the size of columns in a grid?", options: ["grid-columns", "grid-template-columns", "columns", "grid-cols"], answer: 1 },
  { question: "How do you make an element span 2 columns in a grid?", options: ["grid-column: span 2", "column-span: 2", "grid-span: 2", "span-columns: 2"], answer: 0 },
  { question: "Which property is used for animations?", options: ["transition", "animate", "animation", "keyframes"], answer: 2 },
  { question: "How do you create a transition effect?", options: ["transition: property duration", "animate: property duration", "effect: transition property duration", "transform: property duration"], answer: 0 },
  { question: "Which property rotates an element?", options: ["rotate", "transform: rotate", "spin", "rotation"], answer: 1 },
  { question: "How do you scale an element to twice its size?", options: ["scale: 2", "transform: scale(2)", "size: 200%", "zoom: 2"], answer: 1 },
  { question: "Which property is used to change the cursor?", options: ["mouse-pointer", "cursor", "pointer", "mouse-cursor"], answer: 1 },
  { question: "How do you hide an element but keep its space?", options: ["display: none", "visibility: hidden", "opacity: 0", "hidden: true"], answer: 1 },
  { question: "How do you completely hide an element?", options: ["display: none", "visibility: none", "opacity: 0", "hidden: true"], answer: 0 },
  { question: "Which property controls text alignment?", options: ["text-align", "align-text", "text-position", "font-align"], answer: 0 },
  { question: "How do you underline text?", options: ["text-decoration: underline", "font-style: underline", "text-style: underline", "underline: true"], answer: 0 },
  { question: "How do you remove the underline from links?", options: ["a {text-decoration: none}", "a {underline: none}", "a {text-style: none}", "a {decoration: none}"], answer: 0 },
  { question: "Which property adds space between letters?", options: ["letter-spacing", "text-spacing", "word-spacing", "font-spacing"], answer: 0 },
  { question: "Which property adds space between words?", options: ["word-spacing", "text-spacing", "letter-spacing", "font-spacing"], answer: 0 },
  { question: "Which property controls line height?", options: ["line-height", "text-height", "font-height", "spacing"], answer: 0 },
  { question: "How do you make text uppercase?", options: ["text-transform: uppercase", "font-style: uppercase", "text-case: upper", "uppercase: true"], answer: 0 },
  { question: "Which property specifies how to handle white-space inside an element?", options: ["space", "white-space", "text-space", "font-space"], answer: 1 },
  { question: "How do you specify a custom font?", options: ["font-family: 'FontName'", "font: 'FontName'", "custom-font: 'FontName'", "font-face: 'FontName'"], answer: 0 },
  { question: "Which rule allows you to define custom fonts?", options: ["@font-face", "@custom-font", "@import-font", "@font-family"], answer: 0 },
  { question: "How do you import an external stylesheet?", options: ["<link>", "@import", "<style>", "Both A and B"], answer: 3 },
  { question: "Which property specifies the stack order of elements?", options: ["z-index", "stack-order", "layer", "depth"], answer: 0 },
  { question: "How do you center an element horizontally?", options: ["margin: 0 auto", "align: center", "center: true", "position: center"], answer: 0 },
  { question: "Which property specifies the type of box model?", options: ["box-sizing", "box-model", "display-type", "layout"], answer: 0 },
  { question: "What is the default box-sizing value?", options: ["content-box", "border-box", "padding-box", "margin-box"], answer: 0 },
  { question: "How do you include padding and border in element's total width?", options: ["box-sizing: border-box", "box-model: include", "width: 100% + padding", "layout: border-box"], answer: 0 },
  { question: "Which property creates a transparent element?", options: ["opacity", "transparent", "visibility", "clear"], answer: 0 },
  { question: "How do you specify multiple background images?", options: ["background-image: url(img1), url(img2)", "background: url(img1) url(img2)", "background-images: url(img1), url(img2)", "multiple-background: url(img1), url(img2)"], answer: 0 },
  { question: "Which property specifies how background images repeat?", options: ["background-repeat", "repeat", "background-tile", "tile"], answer: 0 },
  { question: "How do you prevent background image repetition?", options: ["background-repeat: no-repeat", "repeat: none", "background-tile: none", "no-tile: true"], answer: 0 },
  { question: "Which property specifies the position of a background image?", options: ["background-position", "background-align", "image-position", "position"], answer: 0 },
  { question: "How do you make a background image fixed during scrolling?", options: ["background-attachment: fixed", "background-fixed: true", "background-scroll: none", "fixed-background: true"], answer: 0 },
  { question: "Which property specifies the size of a background image?", options: ["background-size", "image-size", "background-dimensions", "size"], answer: 0 },
  { question: "How do you make a background image cover the entire element?", options: ["background-size: cover", "background-cover: true", "background-fit: cover", "cover-background: true"], answer: 0 },
  { question: "Which property specifies the origin of a background image?", options: ["background-origin", "origin", "background-position-origin", "image-origin"], answer: 0 },
  { question: "Which property specifies the painting area of a background?", options: ["background-clip", "clip", "background-painting", "paint-area"], answer: 0 },
  { question: "How do you create a linear gradient background?", options: ["background: linear-gradient()", "gradient: linear()", "background-gradient: linear()", "linear-gradient: background()"], answer: 0 },
  { question: "How do you create a radial gradient background?", options: ["background: radial-gradient()", "gradient: radial()", "background-gradient: radial()", "radial-gradient: background()"], answer: 0 },
  { question: "Which property adds shadow to text?", options: ["text-shadow", "font-shadow", "shadow", "text-effect"], answer: 0 },
  { question: "How do you create a multi-column layout?", options: ["columns: 3", "column-count: 3", "multi-column: 3", "layout-columns: 3"], answer: 1 },
  { question: "Which property specifies the gap between columns?", options: ["column-gap", "gap", "column-spacing", "spacing"], answer: 0 },
  { question: "Which property specifies a rule between columns?", options: ["column-rule", "rule", "column-line", "divider"], answer: 0 },
  { question: "How do you specify the width of columns?", options: ["column-width", "width", "columns", "col-width"], answer: 0 },
  { question: "Which property specifies how elements float?", options: ["float", "position", "align", "flow"], answer: 0 },
  { question: "How do you stop elements from floating?", options: ["clear: both", "float: none", "stop-float: true", "clear-floats: true"], answer: 0 },
  { question: "Which property specifies the type of cursor?", options: ["cursor", "mouse-pointer", "pointer", "mouse-cursor"], answer: 0 },
  { question: "How do you create a custom cursor?", options: ["cursor: url()", "pointer: url()", "custom-cursor: url()", "mouse: url()"], answer: 0 },
  { question: "Which property specifies the resizability of an element?", options: ["resize", "scale", "sizeable", "flexible"], answer: 0 },
  { question: "Which property specifies the outline of an element?", options: ["outline", "border-outline", "frame", "line"], answer: 0 },
  { question: "How do you offset an outline?", options: ["outline-offset", "offset", "outline-position", "position-offset"], answer: 0 },
  { question: "Which property specifies the tabbing order?", options: ["tab-index", "z-index", "order", "focus-order"], answer: 0 },
  { question: "How do you create a counter?", options: ["counter-reset", "reset-counter", "start-counter", "init-counter"], answer: 0 },
  { question: "How do you increment a counter?", options: ["counter-increment", "increment-counter", "add-counter", "step-counter"], answer: 0 },
  { question: "Which function displays the value of a counter?", options: ["counter()", "display-counter()", "show-counter()", "get-counter()"], answer: 0 },
  { question: "Which property specifies the type of list marker?", options: ["list-style-type", "list-type", "marker-type", "bullet-type"], answer: 0 },
  { question: "How do you use an image as a list marker?", options: ["list-style-image", "list-image", "marker-image", "bullet-image"], answer: 0 },
  { question: "Which property specifies the position of list markers?", options: ["list-style-position", "marker-position", "bullet-position", "list-position"], answer: 0 },
  { question: "How do you create a table with collapsed borders?", options: ["border-collapse: collapse", "table-border: collapse", "collapse-borders: true", "border: collapse"], answer: 0 },
  { question: "Which property specifies empty cell borders?", options: ["empty-cells", "border-empty", "cell-border", "hide-empty"], answer: 0 },
  { question: "Which property specifies table layout algorithm?", options: ["table-layout", "layout", "display-table", "table-display"], answer: 0 },
  { question: "How do you specify the direction of text?", options: ["direction", "text-direction", "writing-mode", "text-flow"], answer: 0 },
  { question: "Which property specifies line breaking rules?", options: ["word-break", "line-break", "break-word", "text-wrap"], answer: 0 },
  { question: "How do you allow long words to break?", options: ["word-wrap: break-word", "break-word: true", "word-break: break-all", "Both A and C"], answer: 3 },
  { question: "Which property specifies text overflow behavior?", options: ["text-overflow", "overflow-text", "text-truncate", "ellipsis"], answer: 0 },
  { question: "How do you display an ellipsis for overflowed text?", options: ["text-overflow: ellipsis", "overflow: ellipsis", "ellipsis: true", "text-truncate: ellipsis"], answer: 0 },
  { question: "Which property specifies how to handle white-space?", options: ["white-space", "text-space", "space-handling", "whitespace"], answer: 0 },
  { question: "How do you preserve both spaces and line breaks?", options: ["white-space: pre", "space: preserve", "preserve-space: true", "whitespace: keep"], answer: 0 },
  { question: "Which property specifies text rendering optimizations?", options: ["text-rendering", "font-rendering", "render-mode", "text-optimize"], answer: 0 },
  { question: "Which property specifies font smoothing?", options: ["font-smoothing", "text-smoothing", "smooth-font", "antialiased"], answer: 0 },
  { question: "How do you enable hardware acceleration?", options: ["transform: translateZ(0)", "hardware-acceleration: true", "accelerate: gpu", "gpu: hardware"], answer: 0 },
  { question: "Which property specifies how to transform an element?", options: ["transform", "translate", "transition", "morph"], answer: 0 },
  { question: "How do you move an element 50px to the right?", options: ["transform: translateX(50px)", "move: right 50px", "position: relative; left: 50px", "Both A and C"], answer: 3 },
  { question: "Which function rotates an element?", options: ["rotate()", "spin()", "turn()", "rotation()"], answer: 0 },
  { question: "Which function scales an element?", options: ["scale()", "size()", "resize()", "zoom()"], answer: 0 },
  { question: "Which function skews an element?", options: ["skew()", "slant()", "angle()", "tilt()"], answer: 0 },
  { question: "Which property specifies the transform origin?", options: ["transform-origin", "origin", "transform-center", "center-transform"], answer: 0 },
  { question: "Which property specifies 3D transformations?", options: ["transform-style", "3d-transform", "perspective", "transform-3d"], answer: 0 },
  { question: "Which property specifies perspective for 3D transforms?", options: ["perspective", "3d-perspective", "view-distance", "depth"], answer: 0 },
  { question: "Which property specifies backface visibility?", options: ["backface-visibility", "show-back", "visible-back", "back-visibility"], answer: 0 },
  { question: "Which property creates transitions between states?", options: ["transition", "animate", "transform", "morph"], answer: 0 },
  { question: "How do you specify which property to transition?", options: ["transition-property", "property", "transition-element", "animate-property"], answer: 0 },
  { question: "How do you specify transition duration?", options: ["transition-duration", "duration", "transition-time", "animate-duration"], answer: 0 },
  { question: "How do you specify transition timing function?", options: ["transition-timing-function", "timing", "easing", "transition-easing"], answer: 0 },
  { question: "How do you specify transition delay?", options: ["transition-delay", "delay", "transition-wait", "animate-delay"], answer: 0 },
  { question: "Which timing function specifies a cubic-bezier curve?", options: ["cubic-bezier()", "bezier()", "curve()", "easing()"], answer: 0 },
  { question: "Which timing function creates a gradual speed change?", options: ["ease", "linear", "step-start", "ease-in-out"], answer: 3 },
  { question: "Which property creates animations?", options: ["animation", "animate", "keyframes", "transition"], answer: 0 },
  { question: "How do you define keyframes for animations?", options: ["@keyframes", "@animation", "@frames", "@animate"], answer: 0 },
  { question: "How do you specify animation name?", options: ["animation-name", "name", "animate-name", "animation"], answer: 0 },
  { question: "How do you specify animation duration?", options: ["animation-duration", "duration", "animate-time", "animation-time"], answer: 0 },
  { question: "How do you specify animation timing function?", options: ["animation-timing-function", "timing", "easing", "animation-easing"], answer: 0 },
  { question: "How do you specify animation delay?", options: ["animation-delay", "delay", "animate-wait", "animation-wait"], answer: 0 },
  { question: "How do you specify animation iteration count?", options: ["animation-iteration-count", "repeat", "loop", "animation-repeat"], answer: 0 },
  { question: "How do you make an animation run infinitely?", options: ["animation-iteration-count: infinite", "infinite: true", "loop: infinite", "animation-loop: infinite"], answer: 0 },
  { question: "How do you specify animation direction?", options: ["animation-direction", "direction", "animate-direction", "animation-flow"], answer: 0 },
  { question: "How do you specify animation fill mode?", options: ["animation-fill-mode", "fill", "animate-fill", "animation-state"], answer: 0 },
  { question: "How do you pause an animation?", options: ["animation-play-state: paused", "pause: true", "animation-pause", "stop-animation"], answer: 0 },
  { question: "Which property specifies media queries?", options: ["@media", "@screen", "@viewport", "@responsive"], answer: 0 },
  { question: "How do you target screens wider than 768px?", options: ["@media (min-width: 768px)", "@screen (width > 768px)", "@viewport (min: 768px)", "@responsive (width >= 768px)"], answer: 0 },
  { question: "Which property specifies print styles?", options: ["@media print", "@print", "@page", "@printing"], answer: 0 },
  { question: "How do you specify styles for dark mode?", options: ["@media (prefers-color-scheme: dark)", "@dark-mode", "@color-scheme: dark", "@prefers dark"], answer: 0 },
  { question: "Which property specifies viewport settings?", options: ["@viewport", "@media viewport", "@screen", "@responsive"], answer: 0 },
  { question: "Which meta tag controls viewport behavior?", options: ["<meta name='viewport'>", "<meta name='screen'>", "<meta name='responsive'>", "<meta name='display'>"], answer: 0 },
  { question: "How do you make a page responsive?", options: ["Use media queries", "Use relative units", "Use flexible layouts", "All of the above"], answer: 3 },
  { question: "Which unit is relative to font size?", options: ["em", "px", "pt", "in"], answer: 0 },
  { question: "Which unit is relative to root font size?", options: ["rem", "em", "px", "%"], answer: 0 },
  { question: "Which unit is relative to viewport width?", options: ["vw", "%", "em", "ch"], answer: 0 },
  { question: "Which unit is relative to viewport height?", options: ["vh", "%", "em", "rem"], answer: 0 },
  { question: "Which unit is relative to character width?", options: ["ch", "em", "ex", "rem"], answer: 0 },
  { question: "Which unit is relative to x-height?", options: ["ex", "em", "ch", "rem"], answer: 0 },
  { question: "Which selector matches all elements?", options: ["*", "all", "any", "universal"], answer: 0 },
  { question: "Which selector matches by attribute?", options: ["[attr]", "attr()", "getAttribute()", ":attr"], answer: 0 },
  { question: "Which selector matches links that have been visited?", options: [":visited", ":active", ":hover", ":link"], answer: 0 },
  { question: "Which selector matches links being clicked?", options: [":active", ":focus", ":hover", ":click"], answer: 0 },
  { question: "Which selector matches input elements that are checked?", options: [":checked", ":selected", ":active", ":on"], answer: 0 },
  { question: "Which selector matches disabled elements?", options: [":disabled", ":off", ":inactive", ":static"], answer: 0 },
  { question: "Which selector matches empty elements?", options: [":empty", ":blank", ":void", ":none"], answer: 0 },
  { question: "Which selector matches the first child?", options: [":first-child", ":first", ":child(1)", ":nth-child(1)"], answer: 0 },
  { question: "Which selector matches the first of its type?", options: [":first-of-type", ":first-type", ":type-first", ":nth-of-type(1)"], answer: 0 },
  { question: "Which selector matches focused elements?", options: [":focus", ":active", ":selected", ":current"], answer: 0 },
  { question: "Which selector matches elements with hover?", options: [":hover", ":over", ":mouseover", ":active"], answer: 0 },
  { question: "Which selector matches elements without children?", options: [":empty", ":no-children", ":childless", ":blank"], answer: 0 },
  { question: "Which selector matches invalid input?", options: [":invalid", ":error", ":incorrect", ":bad-input"], answer: 0 },
  { question: "Which selector matches the last child?", options: [":last-child", ":last", ":child(end)", ":nth-last-child(1)"], answer: 0 },
  { question: "Which selector matches the last of its type?", options: [":last-of-type", ":last-type", ":type-last", ":nth-last-of-type(1)"], answer: 0 },
  { question: "Which selector matches links not visited?", options: [":link", ":unvisited", ":not(:visited)", "Both A and C"], answer: 3 },
  { question: "Which selector matches elements that are not X?", options: [":not(X)", ":except(X)", ":exclude(X)", ":without(X)"], answer: 0 },
  { question: "Which selector matches the nth child?", options: [":nth-child(n)", ":child(n)", ":nth(n)", ":select-child(n)"], answer: 0 },
  { question: "Which selector matches the nth from last child?", options: [":nth-last-child(n)", ":last-child(n)", ":child-from-end(n)", ":nth-child-from-end(n)"], answer: 0 },
  { question: "Which selector matches the nth of its type?", options: [":nth-of-type(n)", ":type(n)", ":nth-type(n)", ":select-type(n)"], answer: 0 },
  { question: "Which selector matches the nth from last of its type?", options: [":nth-last-of-type(n)", ":last-type(n)", ":type-from-end(n)", ":nth-type-from-end(n)"], answer: 0 },
  { question: "Which selector matches only child elements?", options: [":only-child", ":single-child", ":one-child", ":unique-child"], answer: 0 },
  { question: "Which selector matches only of its type?", options: [":only-of-type", ":single-type", ":one-type", ":unique-type"], answer: 0 },
  { question: "Which selector matches optional form elements?", options: [":optional", ":not(:required)", ":can-omit", ":not-required"], answer: 0 },
  { question: "Which selector matches out-of-range values?", options: [":out-of-range", ":invalid-range", ":range-error", ":not-in-range"], answer: 0 },
  { question: "Which selector matches read-only elements?", options: [":read-only", ":static", ":no-edit", ":readable"], answer: 0 },
  { question: "Which selector matches read-write elements?", options: [":read-write", ":editable", ":can-edit", ":writeable"], answer: 0 },
  { question: "Which selector matches required form elements?", options: [":required", ":must-fill", ":not-optional", ":mandatory"], answer: 0 },
  { question: "Which selector matches valid input?", options: [":valid", ":correct", ":good-input", ":no-error"], answer: 0 },
  { question: "Which pseudo-element styles the first letter?", options: ["::first-letter", ":first-letter", "::first-character", ":first-character"], answer: 0 },
  { question: "Which pseudo-element styles the first line?", options: ["::first-line", ":first-line", "::start-line", ":start-line"], answer: 0 },
  { question: "Which pseudo-element inserts content before?", options: ["::before", ":before", "::prepend", ":prepend"], answer: 0 },
  { question: "Which pseudo-element inserts content after?", options: ["::after", ":after", "::append", ":append"], answer: 0 },
  { question: "Which pseudo-element highlights user selection?", options: ["::selection", ":selection", "::highlight", ":highlight"], answer: 0 },
  { question: "Which pseudo-element styles the placeholder?", options: ["::placeholder", ":placeholder", "::input-placeholder", ":input-placeholder"], answer: 0 },
  { question: "Which pseudo-element styles the marker?", options: ["::marker", ":marker", "::list-marker", ":list-marker"], answer: 0 },
  { question: "Which pseudo-element styles spelling errors?", options: ["::spelling-error", ":spelling-error", "::error", ":error"], answer: 0 },
  { question: "Which pseudo-element styles grammar errors?", options: ["::grammar-error", ":grammar-error", "::error", ":error"], answer: 0 },
  { question: "Which property specifies variable values?", options: ["--variable", "var()", "custom-property", "Both A and B"], answer: 3 },
  { question: "How do you use a CSS variable?", options: ["var(--name)", "--name", "use(--name)", "getVar(--name)"], answer: 0 },
  { question: "Which at-rule imports another stylesheet?", options: ["@import", "@include", "@use", "@link"], answer: 0 },
  { question: "Which at-rule defines font faces?", options: ["@font-face", "@font", "@import-font", "@custom-font"], answer: 0 },
  { question: "Which at-rule defines keyframe animations?", options: ["@keyframes", "@animation", "@frames", "@animate"], answer: 0 },
  { question: "Which at-rule defines media queries?", options: ["@media", "@screen", "@responsive", "@viewport"], answer: 0 },
  { question: "Which at-rule defines page breaks?", options: ["@page", "@print", "@break", "@media print"], answer: 0 },
  { question: "Which at-rule defines supports queries?", options: ["@supports", "@feature", "@check", "@if-supported"], answer: 0 },
  { question: "Which at-rule defines document styles?", options: ["@document", "@page", "@html", "@root"], answer: 0 },
  { question: "Which at-rule defines namespace?", options: ["@namespace", "@xmlns", "@ns", "@prefix"], answer: 0 },
  { question: "Which at-rule defines character sets?", options: ["@charset", "@encoding", "@character-set", "@set-charset"], answer: 0 },
  { question: "How do you make text unselectable?", options: ["user-select: none", "selectable: false", "text-select: none", "no-select: true"], answer: 0 },
  { question: "Which property specifies touch action?", options: ["touch-action", "pointer-action", "gesture-action", "interaction"], answer: 0 },
  { question: "Which property specifies scroll behavior?", options: ["scroll-behavior", "scroll-type", "smooth-scroll", "scroll-motion"], answer: 0 },
  { question: "How do you make smooth scrolling?", options: ["scroll-behavior: smooth", "smooth-scroll: true", "scroll: smooth", "animation: smooth-scroll"], answer: 0 },
  { question: "Which property specifies overscroll behavior?", options: ["overscroll-behavior", "scroll-limit", "bounce-effect", "scroll-boundary"], answer: 0 },
  { question: "Which property specifies pointer events?", options: ["pointer-events", "mouse-events", "interaction-events", "click-events"], answer: 0 },
  { question: "How do you make an element ignore pointer events?", options: ["pointer-events: none", "ignore-events: true", "no-pointer: true", "interaction: none"], answer: 0 },
  { question: "Which property specifies will-change?", options: ["will-change", "optimize", "performance", "hint"], answer: 0 },
  { question: "Which property specifies image rendering?", options: ["image-rendering", "image-quality", "pixelation", "render-quality"], answer: 0 },
  { question: "Which property specifies shape outside?", options: ["shape-outside", "float-shape", "wrap-shape", "text-wrap-shape"], answer: 0 },
  { question: "Which property specifies shape margin?", options: ["shape-margin", "wrap-margin", "float-margin", "text-wrap-margin"], answer: 0 },
  { question: "Which property specifies clip path?", options: ["clip-path", "mask", "cutout", "shape-clip"], answer: 0 },
  { question: "Which property specifies mask image?", options: ["mask-image", "clip-image", "cutout-image", "shape-mask"], answer: 0 },
  { question: "Which property specifies mask mode?", options: ["mask-mode", "mask-type", "mask-style", "mask-rendering"], answer: 0 },
  { question: "Which property specifies mask position?", options: ["mask-position", "mask-offset", "mask-location", "mask-align"], answer: 0 },
  { question: "Which property specifies mask size?", options: ["mask-size", "mask-dimensions", "mask-scale", "mask-resize"], answer: 0 },
  { question: "Which property specifies mask repeat?", options: ["mask-repeat", "mask-tiling", "mask-pattern", "mask-fill"], answer: 0 },
  { question: "Which property specifies mask origin?", options: ["mask-origin", "mask-source", "mask-position-origin", "mask-start"], answer: 0 },
  { question: "Which property specifies mask clip?", options: ["mask-clip", "mask-cut", "mask-boundary", "mask-limits"], answer: 0 },
  { question: "Which property specifies mask composite?", options: ["mask-composite", "mask-blend", "mask-combine", "mask-merge"], answer: 0 },
  { question: "Which property specifies filter effects?", options: ["filter", "effect", "image-filter", "visual-effect"], answer: 0 },
  { question: "Which function blurs an element?", options: ["blur()", "filter-blur()", "gaussian-blur()", "soften()"], answer: 0 },
  { question: "Which function adjusts brightness?", options: ["brightness()", "lighten()", "exposure()", "luminance()"], answer: 0 },
  { question: "Which function adjusts contrast?", options: ["contrast()", "difference()", "clarity()", "vibrance()"], answer: 0 },
  { question: "Which function adds a drop shadow?", options: ["drop-shadow()", "shadow()", "box-shadow()", "text-shadow()"], answer: 0 },
  { question: "Which function converts to grayscale?", options: ["grayscale()", "monochrome()", "bw()", "desaturate()"], answer: 0 },
  { question: "Which function hue-rotates colors?", options: ["hue-rotate()", "color-rotate()", "spin()", "rotate-hue()"], answer: 0 },
  { question: "Which function inverts colors?", options: ["invert()", "negative()", "reverse()", "flip()"], answer: 0 },
  { question: "Which function adjusts opacity?", options: ["opacity()", "transparency()", "alpha()", "fade()"], answer: 0 },
  { question: "Which function saturates colors?", options: ["saturate()", "vibrance()", "intensity()", "colorize()"], answer: 0 },
  { question: "Which function applies sepia tone?", options: ["sepia()", "antique()", "vintage()", "old-style()"], answer: 0 },
  { question: "Which property specifies backdrop filter?", options: ["backdrop-filter", "background-filter", "behind-filter", "rear-filter"], answer: 0 },
  { question: "Which property specifies mix blend mode?", options: ["mix-blend-mode", "blend-mode", "layer-mode", "composite-mode"], answer: 0 },
  { question: "Which property specifies background blend mode?", options: ["background-blend-mode", "bg-blend-mode", "layer-blend-mode", "image-blend-mode"], answer: 0 },
  { question: "Which property specifies isolation?", options: ["isolation", "layer-isolation", "stack-context", "blend-isolation"], answer: 0 },
  { question: "Which property specifies scroll snap type?", options: ["scroll-snap-type", "snap-scroll", "scroll-lock", "snap-points"], answer: 0 },
  { question: "Which property specifies scroll snap align?", options: ["scroll-snap-align", "snap-align", "scroll-align", "snap-position"], answer: 0 },
  { question: "Which property specifies scroll snap stop?", options: ["scroll-snap-stop", "snap-stop", "scroll-stop", "snap-lock"], answer: 0 },
  { question: "Which property specifies scroll margin?", options: ["scroll-margin", "snap-margin", "scroll-padding", "snap-offset"], answer: 0 },
  { question: "Which property specifies scroll padding?", options: ["scroll-padding", "snap-padding", "scroll-margin", "snap-inset"], answer: 0 },
  { question: "Which property specifies column count?", options: ["column-count", "columns", "col-count", "grid-columns"], answer: 0 },
  { question: "Which property specifies column fill?", options: ["column-fill", "fill-columns", "balance-columns", "column-balance"], answer: 0 },
  { question: "Which property specifies column gap?", options: ["column-gap", "gap-columns", "column-spacing", "col-gap"], answer: 0 },
  { question: "Which property specifies column rule?", options: ["column-rule", "rule-columns", "column-line", "col-rule"], answer: 0 },
  { question: "Which property specifies column span?", options: ["column-span", "span-columns", "cross-columns", "col-span"], answer: 0 },
  { question: "Which property specifies column width?", options: ["column-width", "width-columns", "col-width", "grid-column-width"], answer: 0 },
  { question: "Which property specifies break after?", options: ["break-after", "page-break-after", "column-break-after", "all of the above"], answer: 3 },
  { question: "Which property specifies break before?", options: ["break-before", "page-break-before", "column-break-before", "all of the above"], answer: 3 },
  { question: "Which property specifies break inside?", options: ["break-inside", "page-break-inside", "column-break-inside", "all of the above"], answer: 3 },
  { question: "Which property specifies orphans?", options: ["orphans", "widows", "page-break-orphans", "column-break-orphans"], answer: 0 },
  { question: "Which property specifies widows?", options: ["widows", "orphans", "page-break-widows", "column-break-widows"], answer: 0 },
  { question: "Which property specifies quotes?", options: ["quotes", "text-quotes", "quote-marks", "punctuation"], answer: 0 },
  { question: "Which property specifies tab size?", options: ["tab-size", "tab-width", "indent-size", "tab-space"], answer: 0 },
  { question: "Which property specifies text align last?", options: ["text-align-last", "align-last", "last-align", "text-last-align"], answer: 0 },
  { question: "Which property specifies text combine upright?", options: ["text-combine-upright", "combine-text", "upright-text", "text-vertical-combine"], answer: 0 },
  { question: "Which property specifies text decoration color?", options: ["text-decoration-color", "decoration-color", "underline-color", "text-line-color"], answer: 0 },
  { question: "Which property specifies text decoration line?", options: ["text-decoration-line", "decoration-line", "underline-style", "text-line-style"], answer: 0 },
  { question: "Which property specifies text decoration style?", options: ["text-decoration-style", "decoration-style", "underline-type", "text-line-type"], answer: 0 },
  { question: "Which property specifies text emphasis?", options: ["text-emphasis", "emphasis", "text-highlight", "text-focus"], answer: 0 },
  { question: "Which property specifies text indent?", options: ["text-indent", "indent", "paragraph-indent", "first-line-indent"], answer: 0 },
  { question: "Which property specifies text orientation?", options: ["text-orientation", "orientation", "writing-orientation", "text-direction"], answer: 0 },
  { question: "Which property specifies text overflow?", options: ["text-overflow", "overflow-text", "text-truncate", "ellipsis"], answer: 0 },
  { question: "Which property specifies text shadow?", options: ["text-shadow", "shadow-text", "font-shadow", "text-effect"], answer: 0 },
  { question: "Which property specifies text transform?", options: ["text-transform", "transform-text", "case", "text-case"], answer: 0 },
  { question: "Which property specifies text underline position?", options: ["text-underline-position", "underline-position", "text-decoration-position", "decoration-position"], answer: 0 },
  { question: "Which property specifies vertical align?", options: ["vertical-align", "align-vertical", "text-vertical", "baseline-align"], answer: 0 },
  { question: "Which property specifies white space?", options: ["white-space", "space", "text-space", "whitespace"], answer: 0 },
  { question: "Which property specifies word break?", options: ["word-break", "break-word", "text-break", "line-break"], answer: 0 },
  { question: "Which property specifies word spacing?", options: ["word-spacing", "spacing", "text-spacing", "letter-spacing"], answer: 0 },
  { question: "Which property specifies word wrap?", options: ["word-wrap", "wrap", "text-wrap", "line-wrap"], answer: 0 },
  { question: "Which property specifies writing mode?", options: ["writing-mode", "text-direction", "direction-mode", "flow-mode"], answer: 0 },
  { question: "Which property specifies hyphens?", options: ["hyphens", "hyphenate", "text-hyphens", "word-hyphens"], answer: 0 },
  { question: "Which property specifies line break?", options: ["line-break", "break-line", "text-line-break", "word-break"], answer: 0 },
  { question: "Which property specifies overflow wrap?", options: ["overflow-wrap", "word-wrap", "text-wrap", "Both A and B"], answer: 3 },
  { question: "Which property specifies text size adjust?", options: ["text-size-adjust", "font-size-adjust", "size-adjust", "text-adjust"], answer: 0 },
  { question: "Which property specifies user select?", options: ["user-select", "select", "text-select", "selection"], answer: 0 },
  { question: "Which property specifies visibility?", options: ["visibility", "visible", "display", "opacity"], answer: 0 },
  { question: "Which property specifies voice family?", options: ["voice-family", "speak-as", "audio-voice", "speech-voice"], answer: 0 },
  { question: "Which property specifies volume?", options: ["volume", "speak-volume", "audio-volume", "speech-volume"], answer: 0 },
  { question: "Which property specifies speak?", options: ["speak", "speak-as", "speech", "audio"], answer: 0 },
  { question: "Which property specifies speak header?", options: ["speak-header", "header-speak", "table-speak", "speak-as-header"], answer: 0 },
  { question: "Which property specifies speak numeral?", options: ["speak-numeral", "numeral-speak", "number-speak", "speak-as-number"], answer: 0 },
  { question: "Which property specifies speak punctuation?", options: ["speak-punctuation", "punctuation-speak", "symbol-speak", "speak-as-symbol"], answer: 0 },
  { question: "Which property specifies speech rate?", options: ["speech-rate", "rate", "speak-rate", "audio-rate"], answer: 0 },
  { question: "Which property specifies stress?", options: ["stress", "speak-stress", "speech-stress", "audio-stress"], answer: 0 },
  { question: "Which property specifies pitch?", options: ["pitch", "speak-pitch", "speech-pitch", "audio-pitch"], answer: 0 },
  { question: "Which property specifies pitch range?", options: ["pitch-range", "range", "speak-range", "audio-range"], answer: 0 },
  { question: "Which property specifies richness?", options: ["richness", "speak-richness", "speech-richness", "audio-richness"], answer: 0 },
  { question: "Which property specifies voice balance?", options: ["voice-balance", "balance", "speak-balance", "audio-balance"], answer: 0 },
  { question: "Which property specifies voice duration?", options: ["voice-duration", "duration", "speak-duration", "audio-duration"], answer: 0 },
  { question: "Which property specifies voice pitch?", options: ["voice-pitch", "pitch", "speak-pitch", "audio-pitch"], answer: 0 },
  { question: "Which property specifies voice rate?", options: ["voice-rate", "rate", "speak-rate", "audio-rate"], answer: 0 },
  { question: "Which property specifies voice stress?", options: ["voice-stress", "stress", "speak-stress", "audio-stress"], answer: 0 },
  { question: "Which property specifies voice volume?", options: ["voice-volume", "volume", "speak-volume", "audio-volume"], answer: 0 },
  { question: "Which property specifies font feature settings?", options: ["font-feature-settings", "font-variant", "text-features", "typography"], answer: 0 },
  { question: "Which property specifies font kerning?", options: ["font-kerning", "kerning", "text-kerning", "letter-spacing"], answer: 0 },
  { question: "Which property specifies font language override?", options: ["font-language-override", "language", "text-language", "font-lang"], answer: 0 },
  { question: "Which property specifies font size adjust?", options: ["font-size-adjust", "size-adjust", "text-size-adjust", "font-adjust"], answer: 0 },
  { question: "Which property specifies font stretch?", options: ["font-stretch", "stretch", "text-stretch", "font-width"], answer: 0 },
  { question: "Which property specifies font style?", options: ["font-style", "style", "text-style", "font-variant"], answer: 0 },
  { question: "Which property specifies font synthesis?", options: ["font-synthesis", "synthesis", "text-synthesis", "font-variant"], answer: 0 },
  { question: "Which property specifies font variant?", options: ["font-variant", "variant", "text-variant", "font-features"], answer: 0 },
  { question: "Which property specifies font variant alternates?", options: ["font-variant-alternates", "variant-alternates", "text-variant-alternates", "font-feature-alternates"], answer: 0 },
  { question: "Which property specifies font variant caps?", options: ["font-variant-caps", "variant-caps", "text-variant-caps", "font-feature-caps"], answer: 0 },
  { question: "Which property specifies font variant east asian?", options: ["font-variant-east-asian", "variant-east-asian", "text-variant-east-asian", "font-feature-east-asian"], answer: 0 },
  { question: "Which property specifies font variant ligatures?", options: ["font-variant-ligatures", "variant-ligatures", "text-variant-ligatures", "font-feature-ligatures"], answer: 0 },
  { question: "Which property specifies font variant numeric?", options: ["font-variant-numeric", "variant-numeric", "text-variant-numeric", "font-feature-numeric"], answer: 0 },
  { question: "Which property specifies font variant position?", options: ["font-variant-position", "variant-position", "text-variant-position", "font-feature-position"], answer: 0 },
  { question: "Which property specifies font weight?", options: ["font-weight", "weight", "text-weight", "font-bold"], answer: 0 },
  { question: "Which property specifies font display?", options: ["font-display", "display", "text-display", "font-render"], answer: 0 },
  { question: "Which property specifies font smoothing?", options: ["font-smoothing", "smoothing", "text-smoothing", "font-antialiasing"], answer: 0 },
  { question: "Which property specifies text rendering?", options: ["text-rendering", "rendering", "font-rendering", "text-display"], answer: 0 },
  { question: "Which property specifies color scheme?", options: ["color-scheme", "scheme", "preferred-color-scheme", "theme"], answer: 0 },
  { question: "Which property specifies forced color adjustment?", options: ["forced-color-adjust", "color-adjust", "print-color-adjust", "color-mode"], answer: 0 },
  { question: "Which property specifies print color adjust?", options: ["print-color-adjust", "color-adjust", "forced-color-adjust", "color-mode"], answer: 0 },
  { question: "Which property specifies writing mode?", options: ["writing-mode", "text-direction", "direction-mode", "flow-mode"], answer: 0 },
  { question: "Which property specifies direction?", options: ["direction", "text-direction", "writing-direction", "flow-direction"], answer: 0 },
  { question: "Which property specifies unicode bidi?", options: ["unicode-bidi", "bidi", "text-bidi", "direction-control"], answer: 0 },
  { question: "Which property specifies text combine upright?", options: ["text-combine-upright", "combine-text", "upright-text", "text-vertical-combine"], answer: 0 },
  { question: "Which property specifies text orientation?", options: ["text-orientation", "orientation", "writing-orientation", "text-direction"], answer: 0 },
  { question: "Which property specifies ime mode?", options: ["ime-mode", "input-mode", "text-input", "keyboard-mode"], answer: 0 },
  { question: "Which property specifies nav down?", options: ["nav-down", "navigation-down", "focus-down", "tab-down"], answer: 0 },
  { question: "Which property specifies nav left?", options: ["nav-left", "navigation-left", "focus-left", "tab-left"], answer: 0 },
  { question: "Which property specifies nav right?", options: ["nav-right", "navigation-right", "focus-right", "tab-right"], answer: 0 },
  { question: "Which property specifies nav up?", options: ["nav-up", "navigation-up", "focus-up", "tab-up"], answer: 0 },
  { question: "Which property specifies outline offset?", options: ["outline-offset", "offset", "outline-position", "position-offset"], answer: 0 },
  { question: "Which property specifies resize?", options: ["resize", "scale", "sizeable", "flexible"], answer: 0 },
  { question: "Which property specifies text overflow?", options: ["text-overflow", "overflow-text", "text-truncate", "ellipsis"], answer: 0 },
  { question: "Which property specifies overflow x?", options: ["overflow-x", "overflow-horizontal", "horizontal-overflow", "x-overflow"], answer: 0 },
  { question: "Which property specifies overflow y?", options: ["overflow-y", "overflow-vertical", "vertical-overflow", "y-overflow"], answer: 0 },
  { question: "Which property specifies overscroll behavior?", options: ["overscroll-behavior", "scroll-limit", "bounce-effect", "scroll-boundary"], answer: 0 },
  { question: "Which property specifies overscroll behavior x?", options: ["overscroll-behavior-x", "overscroll-x", "scroll-limit-x", "bounce-effect-x"], answer: 0 },
  { question: "Which property specifies overscroll behavior y?", options: ["overscroll-behavior-y", "overscroll-y", "scroll-limit-y", "bounce-effect-y"], answer: 0 },
  { question: "Which property specifies scroll behavior?", options: ["scroll-behavior", "scroll-type", "smooth-scroll", "scroll-motion"], answer: 0 },
  { question: "Which property specifies scroll margin?", options: ["scroll-margin", "snap-margin", "scroll-padding", "snap-offset"], answer: 0 },
  { question: "Which property specifies scroll margin bottom?", options: ["scroll-margin-bottom", "snap-margin-bottom", "scroll-padding-bottom", "snap-offset-bottom"], answer: 0 },
  { question: "Which property specifies scroll margin left?", options: ["scroll-margin-left", "snap-margin-left", "scroll-padding-left", "snap-offset-left"], answer: 0 },
  { question: "Which property specifies scroll margin right?", options: ["scroll-margin-right", "snap-margin-right", "scroll-padding-right", "snap-offset-right"], answer: 0 },
  { question: "Which property specifies scroll margin top?", options: ["scroll-margin-top", "snap-margin-top", "scroll-padding-top", "snap-offset-top"], answer: 0 },
  { question: "Which property specifies scroll padding?", options: ["scroll-padding", "snap-padding", "scroll-margin", "snap-inset"], answer: 0 },
  { question: "Which property specifies scroll padding bottom?", options: ["scroll-padding-bottom", "snap-padding-bottom", "scroll-margin-bottom", "snap-inset-bottom"], answer: 0 },
  { question: "Which property specifies scroll padding left?", options: ["scroll-padding-left", "snap-padding-left", "scroll-margin-left", "snap-inset-left"], answer: 0 },
  { question: "Which property specifies scroll padding right?", options: ["scroll-padding-right", "snap-padding-right", "scroll-margin-right", "snap-inset-right"], answer: 0 },
  { question: "Which property specifies scroll padding top?", options: ["scroll-padding-top", "snap-padding-top", "scroll-margin-top", "snap-inset-top"], answer: 0 },
  { question: "Which property specifies scroll snap align?", options: ["scroll-snap-align", "snap-align", "scroll-align", "snap-position"], answer: 0 },
  { question: "Which property specifies scroll snap stop?", options: ["scroll-snap-stop", "snap-stop", "scroll-stop", "snap-lock"], answer: 0 },
  { question: "Which property specifies scroll snap type?", options: ["scroll-snap-type", "snap-scroll", "scroll-lock", "snap-points"], answer: 0 },
  { question: "Which property specifies scroll snap type x?", options: ["scroll-snap-type-x", "snap-scroll-x", "scroll-lock-x", "snap-points-x"], answer: 0 },
  { question: "Which property specifies scroll snap type y?", options: ["scroll-snap-type-y", "snap-scroll-y", "scroll-lock-y", "snap-points-y"], answer: 0 },
  { question: "Which property specifies touch action?", options: ["touch-action", "pointer-action", "gesture-action", "interaction"], answer: 0 },
  { question: "Which property specifies will change?", options: ["will-change", "optimize", "performance", "hint"], answer: 0 },
  { question: "Which property specifies accent color?", options: ["accent-color", "highlight-color", "focus-color", "active-color"], answer: 0 },
  { question: "Which property specifies align content?", options: ["align-content", "content-align", "flex-align-content", "grid-align-content"], answer: 0 },
  { question: "Which property specifies align items?", options: ["align-items", "items-align", "flex-align-items", "grid-align-items"], answer: 0 },
  { question: "Which property specifies align self?", options: ["align-self", "self-align", "flex-align-self", "grid-align-self"], answer: 0 },
  { question: "Which property specifies all?", options: ["all", "reset", "initial", "default"], answer: 0 },
  { question: "Which property specifies animation?", options: ["animation", "animate", "keyframes", "transition"], answer: 0 },
  { question: "Which property specifies animation delay?", options: ["animation-delay", "delay", "animate-wait", "animation-wait"], answer: 0 },
  { question: "Which property specifies animation direction?", options: ["animation-direction", "direction", "animate-direction", "animation-flow"], answer: 0 },
  { question: "Which property specifies animation duration?", options: ["animation-duration", "duration", "animate-time", "animation-time"], answer: 0 },
  { question: "Which property specifies animation fill mode?", options: ["animation-fill-mode", "fill", "animate-fill", "animation-state"], answer: 0 },
  { question: "Which property specifies animation iteration count?", options: ["animation-iteration-count", "repeat", "loop", "animation-repeat"], answer: 0 },
  { question: "Which property specifies animation name?", options: ["animation-name", "name", "animate-name", "animation"], answer: 0 },
  { question: "Which property specifies animation play state?", options: ["animation-play-state", "play", "animate-play", "animation-state"], answer: 0 },
  { question: "Which property specifies animation timing function?", options: ["animation-timing-function", "timing", "easing", "animation-easing"], answer: 0 },
  { question: "Which property specifies backdrop filter?", options: ["backdrop-filter", "background-filter", "behind-filter", "rear-filter"], answer: 0 },
  { question: "Which property specifies backface visibility?", options: ["backface-visibility", "show-back", "visible-back", "back-visibility"], answer: 0 },
  { question: "Which property specifies background?", options: ["background", "bg", "background-all", "background-properties"], answer: 0 },
  { question: "Which property specifies background attachment?", options: ["background-attachment", "attachment", "bg-attachment", "background-fixed"], answer: 0 },
  { question: "Which property specifies background blend mode?", options: ["background-blend-mode", "bg-blend-mode", "layer-blend-mode", "image-blend-mode"], answer: 0 },
  { question: "Which property specifies background clip?", options: ["background-clip", "clip", "background-painting", "paint-area"], answer: 0 },
  { question: "Which property specifies background color?", options: ["background-color", "bg-color", "background", "color"], answer: 0 },
  { question: "Which property specifies background image?", options: ["background-image", "bg-image", "background", "image"], answer: 0 },
  { question: "Which property specifies background origin?", options: ["background-origin", "origin", "background-position-origin", "image-origin"], answer: 0 },
  { question: "Which property specifies background position?", options: ["background-position", "position", "bg-position", "background-align"], answer: 0 },
  { question: "Which property specifies background repeat?", options: ["background-repeat", "repeat", "bg-repeat", "background-tiling"], answer: 0 },
  { question: "Which property specifies background size?", options: ["background-size", "size", "bg-size", "background-dimensions"], answer: 0 },
  { question: "Which property specifies border?", options: ["border", "border-all", "border-properties", "outline"], answer: 0 },
  { question: "Which property specifies border bottom?", options: ["border-bottom", "bottom-border", "border-b", "border-under"], answer: 0 },
  { question: "Which property specifies border bottom color?", options: ["border-bottom-color", "bottom-border-color", "border-b-color", "border-under-color"], answer: 0 },
  { question: "Which property specifies border bottom left radius?", options: ["border-bottom-left-radius", "bottom-left-border-radius", "border-bl-radius", "border-under-left-radius"], answer: 0 },
  { question: "Which property specifies border bottom right radius?", options: ["border-bottom-right-radius", "bottom-right-border-radius", "border-br-radius", "border-under-right-radius"], answer: 0 },
  { question: "Which property specifies border bottom style?", options: ["border-bottom-style", "bottom-border-style", "border-b-style", "border-under-style"], answer: 0 },
  { question: "Which property specifies border bottom width?", options: ["border-bottom-width", "bottom-border-width", "border-b-width", "border-under-width"], answer: 0 },
  { question: "Which property specifies border collapse?", options: ["border-collapse", "collapse", "table-border-collapse", "border-merge"], answer: 0 },
  { question: "Which property specifies border color?", options: ["border-color", "color", "border-c", "border-line-color"], answer: 0 },
  { question: "Which property specifies border image?", options: ["border-image", "image", "border-img", "border-picture"], answer: 0 },
  { question: "Which property specifies border image outset?", options: ["border-image-outset", "outset", "border-img-outset", "border-picture-outset"], answer: 0 },
  { question: "Which property specifies border image repeat?", options: ["border-image-repeat", "repeat", "border-img-repeat", "border-picture-repeat"], answer: 0 },
  { question: "Which property specifies border image slice?", options: ["border-image-slice", "slice", "border-img-slice", "border-picture-slice"], answer: 0 },
  { question: "Which property specifies border image source?", options: ["border-image-source", "source", "border-img-source", "border-picture-source"], answer: 0 },
  { question: "Which property specifies border image width?", options: ["border-image-width", "width", "border-img-width", "border-picture-width"], answer: 0 },
  { question: "Which property specifies border left?", options: ["border-left", "left-border", "border-l", "border-side"], answer: 0 },
  { question: "Which property specifies border left color?", options: ["border-left-color", "left-border-color", "border-l-color", "border-side-color"], answer: 0 },
  { question: "Which property specifies border left style?", options: ["border-left-style", "left-border-style", "border-l-style", "border-side-style"], answer: 0 },
  { question: "Which property specifies border left width?", options: ["border-left-width", "left-border-width", "border-l-width", "border-side-width"], answer: 0 },
  { question: "Which property specifies border radius?", options: ["border-radius", "radius", "border-round", "corner-radius"], answer: 0 },
  { question: "Which property specifies border right?", options: ["border-right", "right-border", "border-r", "border-side"], answer: 0 },
  { question: "Which property specifies border right color?", options: ["border-right-color", "right-border-color", "border-r-color", "border-side-color"], answer: 0 },
  { question: "Which property specifies border right style?", options: ["border-right-style", "right-border-style", "border-r-style", "border-side-style"], answer: 0 },
  { question: "Which property specifies border right width?", options: ["border-right-width", "right-border-width", "border-r-width", "border-side-width"], answer: 0 },
  { question: "Which property specifies border spacing?", options: ["border-spacing", "spacing", "table-border-spacing", "cell-spacing"], answer: 0 },
  { question: "Which property specifies border style?", options: ["border-style", "style", "border-s", "border-line-style"], answer: 0 },
  { question: "Which property specifies border top?", options: ["border-top", "top-border", "border-t", "border-over"], answer: 0 },
  { question: "Which property specifies border top color?", options: ["border-top-color", "top-border-color", "border-t-color", "border-over-color"], answer: 0 },
  { question: "Which property specifies border top left radius?", options: ["border-top-left-radius", "top-left-border-radius", "border-tl-radius", "border-over-left-radius"], answer: 0 },
  { question: "Which property specifies border top right radius?", options: ["border-top-right-radius", "top-right-border-radius", "border-tr-radius", "border-over-right-radius"], answer: 0 },
  { question: "Which property specifies border top style?", options: ["border-top-style", "top-border-style", "border-t-style", "border-over-style"], answer: 0 },
  { question: "Which property specifies border top width?", options: ["border-top-width", "top-border-width", "border-t-width", "border-over-width"], answer: 0 },
  { question: "Which property specifies border width?", options: ["border-width", "width", "border-w", "border-line-width"], answer: 0 },
  { question: "Which property specifies bottom?", options: ["bottom", "position-bottom", "offset-bottom", "margin-bottom"], answer: 0 },
  { question: "Which property specifies box decoration break?", options: ["box-decoration-break", "decoration-break", "box-break", "fragment-break"], answer: 0 },
  { question: "Which property specifies box shadow?", options: ["box-shadow", "shadow", "box-effect", "drop-shadow"], answer: 0 },
  { question: "Which property specifies box sizing?", options: ["box-sizing", "sizing", "layout-box", "model-box"], answer: 0 },
  { question: "Which property specifies break after?", options: ["break-after", "page-break-after", "column-break-after", "all of the above"], answer: 3 },
  { question: "Which property specifies break before?", options: ["break-before", "page-break-before", "column-break-before", "all of the above"], answer: 3 },
  { question: "Which property specifies break inside?", options: ["break-inside", "page-break-inside", "column-break-inside", "all of the above"], answer: 3 },
  { question: "Which property specifies caption side?", options: ["caption-side", "side", "table-caption-side", "caption-position"], answer: 0 },
  { question: "Which property specifies caret color?", options: ["caret-color", "cursor-color", "text-cursor-color", "input-cursor-color"], answer: 0 },
  { question: "Which property specifies clear?", options: ["clear", "float-clear", "flow-clear", "position-clear"], answer: 0 },
  { question: "Which property specifies clip?", options: ["clip", "cut", "mask", "hide"], answer: 0 },
  { question: "Which property specifies clip path?", options: ["clip-path", "path", "mask-path", "cut-path"], answer: 0 },
  { question: "Which property specifies color?", options: ["color", "text-color", "font-color", "foreground"], answer: 0 },
  { question: "Which property specifies color scheme?", options: ["color-scheme", "scheme", "preferred-color-scheme", "theme"], answer: 0 },
  { question: "Which property specifies column count?", options: ["column-count", "columns", "col-count", "grid-columns"], answer: 0 },
  { question: "Which property specifies column fill?", options: ["column-fill", "fill-columns", "balance-columns", "column-balance"], answer: 0 },
  { question: "Which property specifies column gap?", options: ["column-gap", "gap-columns", "column-spacing", "col-gap"], answer: 0 },
  { question: "Which property specifies column rule?", options: ["column-rule", "rule-columns", "column-line", "col-rule"], answer: 0 },
  { question: "Which property specifies column rule color?", options: ["column-rule-color", "rule-color-columns", "column-line-color", "col-rule-color"], answer: 0 },
  { question: "Which property specifies column rule style?", options: ["column-rule-style", "rule-style-columns", "column-line-style", "col-rule-style"], answer: 0 },
  { question: "Which property specifies column rule width?", options: ["column-rule-width", "rule-width-columns", "column-line-width", "col-rule-width"], answer: 0 },
  { question: "Which property specifies column span?", options: ["column-span", "span-columns", "cross-columns", "col-span"], answer: 0 },
  { question: "Which property specifies column width?", options: ["column-width", "width-columns", "col-width", "grid-column-width"], answer: 0 },
  { question: "Which property specifies content?", options: ["content", "text-content", "pseudo-content", "generated-content"], answer: 0 },
  { question: "Which property specifies counter increment?", options: ["counter-increment", "increment-counter", "add-counter", "step-counter"], answer: 0 },
  { question: "Which property specifies counter reset?", options: ["counter-reset", "reset-counter", "start-counter", "init-counter"], answer: 0 },
  { question: "Which property specifies cursor?", options: ["cursor", "mouse-pointer", "pointer", "mouse-cursor"], answer: 0 },
  { question: "Which property specifies direction?", options: ["direction", "text-direction", "writing-direction", "flow-direction"], answer: 0 },
  { question: "Which property specifies display?", options: ["display", "layout", "render", "show"], answer: 0 },
  { question: "Which property specifies empty cells?", options: ["empty-cells", "border-empty", "cell-border", "hide-empty"], answer: 0 },
  { question: "Which property specifies filter?", options: ["filter", "effect", "image-filter", "visual-effect"], answer: 0 },
  { question: "Which property specifies flex?", options: ["flex", "flexible", "flex-layout", "flex-box"], answer: 0 },
];
