// 200 basic HTML questions for the quiz app
export const htmlQuestions = [
  { question: "What does HTML stand for?", options: ["Hyper Text Markup Language", "Home Tool Markup Language", "Hyperlinks and Text Markup Language", "Hyperlinking Text Mark Language"], answer: 0 },
  { question: "Who is making the Web standards?", options: ["Mozilla", "Microsoft", "The World Wide Web Consortium", "Google"], answer: 2 },
  { question: "Choose the correct HTML element for the largest heading:", options: ["<heading>", "<h6>", "<head>", "<h1>"], answer: 3 },
  { question: "What is the correct HTML element for inserting a line break?", options: ["<break>", "<br>", "<lb>", "<line>"], answer: 1 },
  { question: "What is the correct HTML for adding a background color?", options: ["<body style='background-color:yellow;'>", "<background>yellow</background>", "<body bg='yellow'>", "<bgcolor>yellow</bgcolor>"], answer: 0 },
  { question: "Choose the correct HTML element to define important text:", options: ["<b>", "<i>", "<strong>", "<important>"], answer: 2 },
  { question: "Choose the correct HTML element to define emphasized text:", options: ["<italic>", "<em>", "<i>", "<strong>"], answer: 1 },
  { question: "What is the correct HTML for creating a hyperlink?", options: ["<a>http://www.example.com</a>", "<a href='http://www.example.com'>Example</a>", "<link>http://www.example.com</link>", "<url>http://www.example.com</url>"], answer: 1 },
  { question: "Which character is used to indicate an end tag?", options: ["/", "*", "<", "^"], answer: 0 },
  { question: "How can you open a link in a new tab/browser window?", options: ["<a href='url' new>", "<a href='url' target='_blank'>", "<a href='url' target='new'>", "<a href='url' window='_blank'>"], answer: 1 },
  { question: "Which of these elements are all <table> elements?", options: ["<table> <tr> <tt>", "<thead> <body> <tr>", "<table> <tr> <td>", "<table> <head> <tfoot>"], answer: 2 },
  { question: "How can you make a numbered list?", options: ["<ul>", "<ol>", "<dl>", "<list>"], answer: 1 },
  { question: "How can you make a bulleted list?", options: ["<ol>", "<ul>", "<dl>", "<list>"], answer: 1 },
  { question: "What is the correct HTML for making a text input field?", options: ["<input type='textfield'>", "<input type='text'>", "<textfield>", "<textinput>"], answer: 1 },
  { question: "What is the correct HTML for making a checkbox?", options: ["<input type='check'>", "<checkbox>", "<input type='checkbox'>", "<input type='cb'>"], answer: 2 },
  { question: "What is the correct HTML for making a drop-down list?", options: ["<input type='list'>", "<input type='dropdown'>", "<select>", "<list>"], answer: 2 },
  { question: "What is the correct HTML for making a text area?", options: ["<input type='textarea'>", "<textarea>", "<input type='textbox'>", "<textbox>"], answer: 1 },
  { question: "What is the correct HTML for inserting an image?", options: ["<img href='image.gif' alt='MyImage'>", "<img alt='MyImage'>image.gif</img>", "<img src='image.gif' alt='MyImage'>", "<image src='image.gif' alt='MyImage'>"], answer: 2 },
  { question: "What is the correct HTML for inserting a background image?", options: ["<body bg='background.gif'>", "<background img='background.gif'>", "<body style='background-image:url(background.gif)'>", "<img background='background.gif'>"], answer: 2 },
  { question: "An <iframe> is used to display a web page within a web page.", options: ["True", "False", "Only in HTML5", "Only in XHTML"], answer: 0 },
  { question: "Which HTML element is used to specify a footer for a document or section?", options: ["<bottom>", "<footer>", "<section>", "<foot>"], answer: 1 },
  { question: "Which HTML attribute specifies an alternate text for an image, if the image cannot be displayed?", options: ["title", "src", "alt", "longdesc"], answer: 2 },
  { question: "Which HTML element is used to define navigation links?", options: ["<navigate>", "<nav>", "<navigation>", "<links>"], answer: 1 },
  { question: "Which HTML element is used to define important text?", options: ["<b>", "<important>", "<strong>", "<imp>"], answer: 2 },
  { question: "Which HTML element is used to define a table row?", options: ["<row>", "<tr>", "<td>", "<table-row>"], answer: 1 },
  { question: "Which HTML element is used to define a table cell?", options: ["<cell>", "<td>", "<tr>", "<table-cell>"], answer: 1 },
  { question: "Which HTML element is used to define a table header?", options: ["<th>", "<thead>", "<header>", "<table-header>"], answer: 0 },
  { question: "Which HTML element is used to define a table body?", options: ["<tbody>", "<body>", "<tablebody>", "<tb>"], answer: 0 },
  { question: "Which HTML element is used to define a table footer?", options: ["<tfoot>", "<footer>", "<tablefooter>", "<tf>"], answer: 0 },
  { question: "Which HTML element is used to define a list item?", options: ["<li>", "<item>", "<list>", "<ul>"], answer: 0 },
  { question: "Which HTML element is used to define an unordered list?", options: ["<ul>", "<ol>", "<list>", "<li>"], answer: 0 },
  { question: "Which HTML element is used to define an ordered list?", options: ["<ol>", "<ul>", "<list>", "<li>"], answer: 0 },
  { question: "Which HTML element is used to define a description list?", options: ["<dl>", "<list>", "<desc>", "<ul>"], answer: 0 },
  { question: "Which HTML element is used to define a term in a description list?", options: ["<dt>", "<term>", "<desc>", "<dl>"], answer: 0 },
  { question: "Which HTML element is used to define a description in a description list?", options: ["<dd>", "<desc>", "<dl>", "<dt>"], answer: 0 },
  { question: "Which HTML element is used to define a section in a document?", options: ["<section>", "<div>", "<article>", "<span>"], answer: 0 },
  { question: "Which HTML element is used to define an article?", options: ["<article>", "<section>", "<div>", "<span>"], answer: 0 },
  { question: "Which HTML element is used to define emphasized text?", options: ["<em>", "<i>", "<strong>", "<b>"], answer: 0 },
  { question: "Which HTML element is used to define bold text?", options: ["<b>", "<strong>", "<em>", "<i>"], answer: 0 },
  { question: "Which HTML element is used to define italic text?", options: ["<i>", "<em>", "<strong>", "<b>"], answer: 0 },
  { question: "Which HTML element is used to define a line break?", options: ["<br>", "<lb>", "<break>", "<line>"], answer: 0 },
  { question: "Which HTML element is used to define a horizontal rule?", options: ["<hr>", "<line>", "<horizontal>", "<rule>"], answer: 0 },
  { question: "Which HTML element is used to define a comment?", options: ["<!-- comment -->", "<comment>", "// comment", "# comment"], answer: 0 },
  { question: "Which HTML element is used to define a blockquote?", options: ["<blockquote>", "<quote>", "<bq>", "<block>"], answer: 0 },
  { question: "Which HTML element is used to define a citation?", options: ["<cite>", "<citation>", "<ref>", "<reference>"], answer: 0 },
  { question: "Which HTML element is used to define a code snippet?", options: ["<code>", "<snippet>", "<pre>", "<samp>"], answer: 0 },
  { question: "Which HTML element is used to define a keyboard input?", options: ["<kbd>", "<key>", "<input>", "<keyboard>"], answer: 0 },
  { question: "Which HTML element is used to define a sample output?", options: ["<samp>", "<output>", "<sample>", "<result>"], answer: 0 },
  { question: "Which HTML element is used to define a variable?", options: ["<var>", "<variable>", "<v>", "<val>"], answer: 0 },
  { question: "Which HTML element is used to define a time?", options: ["<time>", "<date>", "<datetime>", "<clock>"], answer: 0 },
  { question: "Which HTML element is used to define a progress bar?", options: ["<progress>", "<bar>", "<meter>", "<range>"], answer: 0 },
  { question: "Which HTML element is used to define a meter?", options: ["<meter>", "<progress>", "<bar>", "<range>"], answer: 0 },
  { question: "Which HTML element is used to define a dialog box or window?", options: ["<dialog>", "<window>", "<box>", "<modal>"], answer: 0 },
  { question: "Which HTML element is used to define a summary for a <details> element?", options: ["<summary>", "<details>", "<info>", "<caption>"], answer: 0 },
  { question: "Which HTML element is used to define a caption for a <table> element?", options: ["<caption>", "<title>", "<summary>", "<head>"], answer: 0 },
  { question: "Which HTML element is used to define a figure?", options: ["<figure>", "<fig>", "<image>", "<img>"], answer: 0 },
  { question: "Which HTML element is used to define a caption for a <figure> element?", options: ["<figcaption>", "<caption>", "<figurecaption>", "<fig>"], answer: 0 },
  { question: "Which HTML element is used to define a contact information for the author/owner of a document?", options: ["<address>", "<contact>", "<info>", "<author>"], answer: 0 },
  { question: "Which HTML element is used to define a script?", options: ["<script>", "<js>", "<javascript>", "<code>"], answer: 0 },
  { question: "Which HTML element is used to define a style information?", options: ["<style>", "<css>", "<stylesheet>", "<link>"], answer: 0 },
  { question: "Which HTML element is used to define a link to an external resource?", options: ["<link>", "<a>", "<resource>", "<external>"], answer: 0 },
  { question: "Which HTML element is used to define a base URL for all relative URLs in a document?", options: ["<base>", "<url>", "<href>", "<link>"], answer: 0 },
  { question: "Which HTML element is used to define a head section of a document?", options: ["<head>", "<header>", "<section>", "<top>"], answer: 0 },
  { question: "Which HTML element is used to define a body section of a document?", options: ["<body>", "<main>", "<section>", "<content>"], answer: 0 },
  { question: "Which HTML element is used to define a main content of a document?", options: ["<main>", "<body>", "<section>", "<content>"], answer: 0 },
  { question: "Which HTML element is used to define a header for a document or section?", options: ["<header>", "<head>", "<section>", "<top>"], answer: 0 },
  { question: "Which HTML element is used to define a footer for a document or section?", options: ["<footer>", "<foot>", "<bottom>", "<section>"], answer: 0 },
  { question: "Which HTML element is used to define a navigation links?", options: ["<nav>", "<navigate>", "<links>", "<navigation>"], answer: 0 },
  { question: "Which HTML element is used to define a section in a document?", options: ["<section>", "<div>", "<article>", "<span>"], answer: 0 },
  { question: "Which HTML element is used to define an aside content?", options: ["<aside>", "<side>", "<sidebar>", "<content>"], answer: 0 },
  { question: "Which HTML element is used to define a data list?", options: ["<datalist>", "<list>", "<data>", "<ul>"], answer: 0 },
  { question: "Which HTML element is used to define an option in a drop-down list?", options: ["<option>", "<choice>", "<select>", "<item>"], answer: 0 },
  { question: "Which HTML element is used to define a group of related options in a drop-down list?", options: ["<optgroup>", "<group>", "<options>", "<selectgroup>"], answer: 0 },
  { question: "Which HTML element is used to define a form?", options: ["<form>", "<input>", "<fieldset>", "<forms>"], answer: 0 },
  { question: "Which HTML element is used to define an input field?", options: ["<input>", "<field>", "<textbox>", "<text>"], answer: 0 },
  { question: "Which HTML element is used to define a label for an input element?", options: ["<label>", "<inputlabel>", "<fieldlabel>", "<formlabel>"], answer: 0 },
  { question: "Which HTML element is used to define a fieldset?", options: ["<fieldset>", "<fields>", "<set>", "<fieldsetgroup>"], answer: 0 },
  { question: "Which HTML element is used to define a legend for a fieldset?", options: ["<legend>", "<caption>", "<title>", "<label>"], answer: 0 },
  { question: "Which HTML element is used to define a button?", options: ["<button>", "<input>", "<btn>", "<pushbutton>"], answer: 0 },
  { question: "Which HTML element is used to define an output?", options: ["<output>", "<result>", "<display>", "<show>"], answer: 0 },
  { question: "Which HTML element is used to define a datalist?", options: ["<datalist>", "<list>", "<data>", "<ul>"], answer: 0 },
  { question: "Which HTML element is used to define a keygen?", options: ["<keygen>", "<key>", "<generate>", "<gen>"], answer: 0 },
  { question: "Which HTML element is used to define a menu?", options: ["<menu>", "<ul>", "<list>", "<menulist>"], answer: 0 },
  { question: "Which HTML element is used to define a menuitem?", options: ["<menuitem>", "<item>", "<menu>", "<listitem>"], answer: 0 },
  { question: "Which HTML element is used to define a template?", options: ["<template>", "<temp>", "<tmpl>", "<tpl>"], answer: 0 },
  { question: "Which HTML element is used to define a slot?", options: ["<slot>", "<placeholder>", "<slotitem>", "<slotgroup>"], answer: 0 },
  { question: "Which HTML tag is used to embed a video in HTML5?", options: ["<media>", "<video>", "<movie>", "<embed>"], answer: 1 },
  { question: "Which HTML tag is used to embed audio in HTML5?", options: ["<media>", "<audio>", "<sound>", "<embed>"], answer: 1 },
  { question: "Which attribute is used to specify that an input field must be filled out?", options: ["validate", "required", "placeholder", "formvalidate"], answer: 1 },
  { question: "Which HTML tag is used to display a scalar measurement within a known range?", options: ["<meter>", "<progress>", "<range>", "<scale>"], answer: 0 },
  { question: "Which HTML tag is used to display a progress bar?", options: ["<progress>", "<meter>", "<bar>", "<range>"], answer: 0 },
  { question: "Which HTML tag is used to define a client-side image map?", options: ["<map>", "<imagemap>", "<area>", "<imgmap>"], answer: 0 },
  { question: "Which HTML tag is used to define an area inside an image map?", options: ["<area>", "<maparea>", "<zone>", "<imgarea>"], answer: 0 },
  { question: "Which HTML tag is used to define a parameter for an object?", options: ["<param>", "<parameter>", "<objectparam>", "<objparam>"], answer: 0 },
  { question: "Which HTML tag is used to define a command button that a user can invoke?", options: ["<command>", "<button>", "<input>", "<invoke>"], answer: 0 },
  { question: "Which HTML tag is used to define a list of pre-defined options for input controls?", options: ["<datalist>", "<list>", "<options>", "<choices>"], answer: 0 },
  { question: "Which HTML tag is used to define a group of related options in a drop-down list?", options: ["<optgroup>", "<group>", "<options>", "<choices>"], answer: 0 },
  { question: "Which HTML tag is used to define a ruby annotation?", options: ["<ruby>", "<annotation>", "<rt>", "<rb>"], answer: 0 },
  { question: "Which HTML tag is used to define an explanation/pronunciation of characters (for East Asian typography)?", options: ["<rt>", "<rp>", "<ruby>", "<explain>"], answer: 0 },
  { question: "Which HTML tag is used to define what to show in browsers that do not support ruby annotations?", options: ["<rp>", "<rt>", "<ruby>", "<nosupport>"], answer: 0 },
  { question: "Which HTML tag is used to define a bidirectional override?", options: ["<bdo>", "<bdi>", "<dir>", "<override>"], answer: 0 },
  { question: "Which HTML tag is used to define an embedded object?", options: ["<object>", "<embed>", "<iframe>", "<media>"], answer: 0 },
  { question: "Which HTML tag is used to define a container for external applications (like a plug-in)?", options: ["<object>", "<embed>", "<iframe>", "<media>"], answer: 1 },
  { question: "Which HTML tag is used to define a scalar measurement within a known range?", options: ["<meter>", "<progress>", "<range>", "<scale>"], answer: 0 },
  { question: "Which HTML tag is used to define a short inline quotation?", options: ["<q>", "<quote>", "<blockquote>", "<inlinequote>"], answer: 0 },
  { question: "Which HTML tag is used to define a variable part of a URL?", options: ["<var>", "<url>", "<param>", "<part>"], answer: 0 },
  { question: "Which HTML tag is used to define a sample output from a computer program?", options: ["<samp>", "<output>", "<result>", "<sample>"], answer: 0 },
  { question: "Which HTML tag is used to define a keyboard input?", options: ["<kbd>", "<key>", "<input>", "<keyboard>"], answer: 0 },
  { question: "Which HTML tag is used to define a variable?", options: ["<var>", "<variable>", "<v>", "<val>"], answer: 0 },
  { question: "Which HTML tag is used to define a time/date?", options: ["<time>", "<date>", "<datetime>", "<clock>"], answer: 0 },
  { question: "Which HTML tag is used to define a contact information for the author/owner of a document?", options: ["<address>", "<contact>", "<info>", "<author>"], answer: 0 },
  { question: "Which HTML tag is used to define a subscripted text?", options: ["<sub>", "<sup>", "<subscript>", "<small>"], answer: 0 },
  { question: "Which HTML tag is used to define a superscripted text?", options: ["<sup>", "<sub>", "<superscript>", "<big>"], answer: 0 },
  { question: "Which HTML tag is used to define a marked/highlighted text?", options: ["<mark>", "<highlight>", "<em>", "<strong>"], answer: 0 },
  { question: "Which HTML tag is used to define a deleted text?", options: ["<del>", "<delete>", "<remove>", "<strike>"], answer: 0 },
  { question: "Which HTML tag is used to define an inserted text?", options: ["<ins>", "<insert>", "<add>", "<u>"], answer: 0 },
  { question: "Which HTML tag is used to define a smaller text?", options: ["<small>", "<tiny>", "<min>", "<smaller>"], answer: 0 },
  { question: "Which HTML tag is used to define a larger text?", options: ["<big>", "<large>", "<max>", "<bigger>"], answer: 0 },
  { question: "Which HTML tag is used to define a section that is quoted from another source?", options: ["<blockquote>", "<quote>", "<q>", "<cite>"], answer: 0 },
  { question: "Which HTML tag is used to define a citation?", options: ["<cite>", "<citation>", "<ref>", "<reference>"], answer: 0 },
  { question: "Which HTML tag is used to define a definition term?", options: ["<dfn>", "<def>", "<define>", "<term>"], answer: 0 },
  { question: "Which HTML tag is used to define a definition description?", options: ["<dd>", "<desc>", "<define>", "<term>"], answer: 0 },
  { question: "Which HTML tag is used to define a definition list?", options: ["<dl>", "<list>", "<deflist>", "<dlist>"], answer: 0 },
  { question: "Which HTML tag is used to define a definition term?", options: ["<dt>", "<term>", "<define>", "<dfn>"], answer: 0 },
  { question: "Which HTML tag is used to define a figure?", options: ["<figure>", "<fig>", "<image>", "<img>"], answer: 0 },
  { question: "Which HTML tag is used to define a caption for a <figure> element?", options: ["<figcaption>", "<caption>", "<figurecaption>", "<fig>"], answer: 0 },
  { question: "Which HTML tag is used to define a script?", options: ["<script>", "<js>", "<javascript>", "<code>"], answer: 0 },
  { question: "Which HTML tag is used to define a style information?", options: ["<style>", "<css>", "<stylesheet>", "<link>"], answer: 0 },
  { question: "Which HTML tag is used to define a link to an external resource?", options: ["<link>", "<a>", "<resource>", "<external>"], answer: 0 },
  { question: "Which HTML tag is used to define a base URL for all relative URLs in a document?", options: ["<base>", "<url>", "<href>", "<link>"], answer: 0 },
  { question: "Which HTML tag is used to define a head section of a document?", options: ["<head>", "<header>", "<section>", "<top>"], answer: 0 },
  { question: "Which HTML tag is used to define a body section of a document?", options: ["<body>", "<main>", "<section>", "<content>"], answer: 0 },
  { question: "Which HTML tag is used to define a main content of a document?", options: ["<main>", "<body>", "<section>", "<content>"], answer: 0 },
  { question: "Which HTML tag is used to define a header for a document or section?", options: ["<header>", "<head>", "<section>", "<top>"], answer: 0 },
  { question: "Which HTML tag is used to define a footer for a document or section?", options: ["<footer>", "<foot>", "<bottom>", "<section>"], answer: 0 },
  { question: "Which HTML tag is used to define a navigation links?", options: ["<nav>", "<navigate>", "<links>", "<navigation>"], answer: 0 },
  { question: "Which HTML tag is used to define a section in a document?", options: ["<section>", "<div>", "<article>", "<span>"], answer: 0 },
  { question: "Which HTML tag is used to define an aside content?", options: ["<aside>", "<side>", "<sidebar>", "<content>"], answer: 0 },
  { question: "Which HTML tag is used to define a data list?", options: ["<datalist>", "<list>", "<data>", "<ul>"], answer: 0 },
  { question: "Which HTML tag is used to define an option in a drop-down list?", options: ["<option>", "<choice>", "<select>", "<item>"], answer: 0 },
  { question: "Which HTML tag is used to define a group of related options in a drop-down list?", options: ["<optgroup>", "<group>", "<options>", "<choices>"], answer: 0 },
  { question: "Which HTML tag is used to define a form?", options: ["<form>", "<input>", "<fieldset>", "<forms>"], answer: 0 },
  { question: "Which HTML tag is used to define an input field?", options: ["<input>", "<field>", "<textbox>", "<text>"], answer: 0 },
  { question: "Which HTML5 element is used to draw graphics via scripting (usually JavaScript)?", options: ["<canvas>", "<svg>", "<draw>", "<graphics>"], answer: 0 },
  { question: "Which HTML5 element is used for scalable vector graphics?", options: ["<svg>", "<canvas>", "<vector>", "<graphics>"], answer: 0 },
  { question: "Which attribute is used to specify that an audio or video should start playing as soon as it is ready?", options: ["autoplay", "play", "start", "run"], answer: 0 },
  { question: "Which attribute is used to specify that an audio or video should play again each time it is finished?", options: ["repeat", "loop", "cycle", "replay"], answer: 1 },
  { question: "Which attribute is used to specify that an audio or video should be muted?", options: ["muted", "mute", "silence", "soundoff"], answer: 0 },
  { question: "Which HTML5 element is used to embed external content at a specific point in the document?", options: ["<iframe>", "<embed>", "<object>", "<import>"], answer: 1 },
  { question: "Which HTML5 API allows web pages to store data locally within the user's browser?", options: ["localStorage", "sessionStorage", "webStorage", "all of the above"], answer: 3 },
  { question: "Which HTML5 API allows a web page to register itself for offline use?", options: ["AppCache", "ServiceWorker", "WebWorker", "Manifest"], answer: 1 },
  { question: "Which HTML5 element is used to define a container for external (non-HTML) applications?", options: ["<object>", "<embed>", "<applet>", "<external>"], answer: 0 },
  { question: "Which HTML5 attribute is used to specify that a form field should have input focus when the page loads?", options: ["autofocus", "focus", "selected", "active"], answer: 0 },
  { question: "Which HTML5 attribute is used to specify that a form field should be completed before submitting?", options: ["required", "validate", "mustfill", "mandatory"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a date?", options: ["date", "datetime", "calendar", "datepicker"], answer: 0 },
  { question: "Which HTML5 input type is used for entering an email address?", options: ["email", "mail", "text", "input"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a URL?", options: ["url", "link", "web", "address"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a color?", options: ["color", "colour", "hex", "rgb"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a telephone number?", options: ["tel", "phone", "number", "mobile"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a range of values?", options: ["range", "slider", "interval", "scale"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a search query?", options: ["search", "find", "query", "input"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a password?", options: ["password", "pass", "secret", "hidden"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a number?", options: ["number", "num", "digit", "value"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a month?", options: ["month", "date", "calendar", "time"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a week?", options: ["week", "date", "calendar", "time"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a time?", options: ["time", "date", "clock", "hour"], answer: 0 },
  { question: "Which HTML5 input type is used for entering a datetime-local?", options: ["datetime-local", "datetime", "date", "time"], answer: 0 },
  { question: "Which HTML5 element is used to define a navigation section?", options: ["<nav>", "<navigation>", "<menu>", "<links>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is tangentially related to the content around it?", options: ["<aside>", "<section>", "<article>", "<div>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that forms an independent part of a document or site?", options: ["<article>", "<section>", "<aside>", "<div>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of navigation links?", options: ["<nav>", "<navigation>", "<menu>", "<links>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is related to the main content but could be considered separate?", options: ["<aside>", "<section>", "<article>", "<div>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is the main content of the document?", options: ["<main>", "<body>", "<section>", "<content>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a header for a document or section?", options: ["<header>", "<head>", "<section>", "<top>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a footer for a document or section?", options: ["<footer>", "<foot>", "<bottom>", "<section>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a navigation links?", options: ["<nav>", "<navigate>", "<links>", "<navigation>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a section in a document?", options: ["<section>", "<div>", "<article>", "<span>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is an aside content?", options: ["<aside>", "<side>", "<sidebar>", "<content>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a data list?", options: ["<datalist>", "<list>", "<data>", "<ul>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is an option in a drop-down list?", options: ["<option>", "<choice>", "<select>", "<item>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a group of related options in a drop-down list?", options: ["<optgroup>", "<group>", "<options>", "<choices>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is a form?", options: ["<form>", "<input>", "<fieldset>", "<forms>"], answer: 0 },
  { question: "Which HTML5 element is used to define a section of content that is an input field?", options: ["<input>", "<field>", "<textbox>", "<text>"], answer: 0 },
  { question: "How do you make an image clickable, so it links to another page?", options: ["Wrap <img> in <a>", "Add href to <img>", "Use <link>", "Use <button>"], answer: 0 },
  { question: "What will happen if you omit the <!DOCTYPE html> declaration?", options: ["Browser uses quirks mode", "Nothing", "Page loads faster", "HTML5 features are enabled"], answer: 0 },
  { question: "Who is responsible for maintaining the HTML standard?", options: ["W3C", "Mozilla", "Google", "Microsoft"], answer: 0 },
  { question: "How can you make a section collapsible in HTML5?", options: ["<details>", "<collapse>", "<section collapsible>", "<summary>"], answer: 0 },
  { question: "What is the effect of the 'download' attribute on an <a> tag?", options: ["Forces file download", "Opens in new tab", "Disables link", "Adds a tooltip"], answer: 0 },
  { question: "Who invented the first version of HTML?", options: ["Tim Berners-Lee", "Bill Gates", "Brendan Eich", "Marc Andreessen"], answer: 0 },
  { question: "Assume you want to group several form controls and labels. Which tag should you use?", options: ["<fieldset>", "<group>", "<formgroup>", "<section>"], answer: 0 },
  { question: "Let's say you want to provide a fallback for browsers that don't support <video>. Where do you put the fallback text?", options: ["Between <video>...</video>", "In a <noscript>", "In a <fallback>", "After </video>"], answer: 0 },
  { question: "Consider a <table> with no <thead> or <tbody>. What happens?", options: ["Browser creates them automatically", "Table won't render", "Rows are ignored", "Table is invalid"], answer: 0 },
  { question: "How do you specify a language for a page in HTML?", options: ["<html lang='en'>", "<meta lang='en'>", "<body lang='en'>", "<lang>en</lang>"], answer: 0 },
  { question: "What is the default display value of a <div> element?", options: ["block", "inline", "inline-block", "none"], answer: 0 },
  { question: "Who determines the default styles for HTML elements?", options: ["Browser", "W3C", "User", "OS"], answer: 0 },
  { question: "Assume you want to add a tooltip to text. Which attribute do you use?", options: ["title", "tooltip", "alt", "info"], answer: 0 },
  { question: "Let's say you want to make a link open in a new tab. Which attribute do you use?", options: ["target='_blank'", "newtab", "rel='new'", "window='_blank'"], answer: 0 },
  { question: "Consider a <form> with no action attribute. What happens on submit?", options: ["Page reloads", "Form does nothing", "Form submits to same URL", "Form is invalid"], answer: 2 },
  { question: "How do you make a text input required?", options: ["required attribute", "mustfill attribute", "validate attribute", "obligatory attribute"], answer: 0 },
  { question: "What is the effect of the 'readonly' attribute on an input?", options: ["Cannot be changed", "Cannot be submitted", "Hidden", "Disabled"], answer: 0 },
  { question: "Who can see the content inside a <noscript> tag?", options: ["Users with JS disabled", "Everyone", "No one", "Only admins"], answer: 0 },
  { question: "Assume you want to add a favicon. Which tag do you use?", options: ["<link rel='icon'>", "<favicon>", "<icon>", "<headicon>"], answer: 0 },
  { question: "Let's say you want to make a button submit a form. What type should it be?", options: ["submit", "button", "reset", "send"], answer: 0 },
  { question: "Consider a <ul> with no <li> children. What happens?", options: ["Renders nothing", "Shows empty bullets", "Shows error", "Shows numbers"], answer: 0 },
  { question: "How do you make a radio button selected by default?", options: ["checked attribute", "selected attribute", "default attribute", "active attribute"], answer: 0 },
  { question: "What is the effect of the 'disabled' attribute on a button?", options: ["Cannot be clicked", "Hidden", "Greyed out but clickable", "Submits form"], answer: 0 },
  { question: "Assume you want to add a comment in HTML. What syntax do you use?", options: ["<!-- comment -->", "// comment", "# comment", "/* comment */"], answer: 0 },
  { question: "Consider a <meta charset='UTF-8'> tag. What does it do?", options: ["Sets character encoding", "Sets page title", "Sets language", "Sets viewport"], answer: 0 },
  { question: "How do you make a link download a file instead of navigating?", options: ["download attribute", "href attribute", "target attribute", "rel attribute"], answer: 0 },
  { question: "What is the effect of the 'multiple' attribute on a file input?", options: ["Allows multiple files", "Allows only one file", "Disables input", "Hides input"], answer: 0 },
  { question: "Assume you want to make a section collapsible. Which elements do you use?", options: ["<details> and <summary>", "<section> and <aside>", "<div> and <span>", "<nav> and <ul>"], answer: 0 },
  { question: "Let's say you want to add a placeholder to an input. Which attribute do you use?", options: ["placeholder", "alt", "title", "label"], answer: 0 },
  { question: "Consider a <progress> element. What does the 'max' attribute do?", options: ["Sets maximum value", "Sets minimum value", "Sets current value", "Sets step size"], answer: 0 },
  { question: "How do you make a checkbox checked by default?", options: ["checked attribute", "selected attribute", "default attribute", "active attribute"], answer: 0 },
  { question: "What is the effect of the 'autofocus' attribute on an input?", options: ["Focuses on load", "Disables input", "Hides input", "Submits form"], answer: 0 },
  { question: "Assume you want to make a field required. Which attribute do you use?", options: ["required", "mustfill", "validate", "obligatory"], answer: 0 },
  { question: "Let's say you want to add a label to an input. Which tag do you use?", options: ["<label>", "<input>", "<span>", "<formlabel>"], answer: 0 },
  { question: "Consider a <select> element. What does the 'multiple' attribute do?", options: ["Allows multiple selections", "Allows only one selection", "Disables select", "Hides select"], answer: 0 },
  { question: "How do you make a password input show dots instead of text?", options: ["type='password'", "type='hidden'", "type='secure'", "type='dot'"], answer: 0 },
  { question: "What is the effect of the 'pattern' attribute on an input?", options: ["Validates input format", "Sets input color", "Sets input size", "Disables input"], answer: 0 },
  { question: "Assume you want to make a field read-only. Which attribute do you use?", options: ["readonly", "disabled", "hidden", "static"], answer: 0 },
  { question: "Let's say you want to add a caption to a table. Which tag do you use?", options: ["<caption>", "<title>", "<summary>", "<head>"], answer: 0 },
  { question: "Consider a <form> with method='post'. Where is the data sent?", options: ["To the server", "To the client", "Nowhere", "To the browser"], answer: 0 },
  { question: "How do you make a text area span multiple lines?", options: ["rows attribute", "cols attribute", "lines attribute", "height attribute"], answer: 0 },
  { question: "What is the effect of the 'step' attribute on a number input?", options: ["Sets increment value", "Sets minimum value", "Sets maximum value", "Sets default value"], answer: 0 },
  { question: "Assume you want to make a field disabled. Which attribute do you use?", options: ["disabled", "readonly", "hidden", "static"], answer: 0 },
  { question: "Let's say you want to add a summary to a <details> element. Which tag do you use?", options: ["<summary>", "<caption>", "<title>", "<head>"], answer: 0 },
  { question: "Consider a <form> with enctype='multipart/form-data'. What is it used for?", options: ["File uploads", "Text only", "JSON data", "XML data"], answer: 0 },
  { question: "How do you make a field hidden from the user but still submitted with the form?", options: ["type='hidden'", "type='invisible'", "type='none'", "type='secret'"], answer: 0 },
  { question: "What is the effect of the 'min' attribute on a number input?", options: ["Sets minimum value", "Sets maximum value", "Sets default value", "Sets increment value"], answer: 0 },
  { question: "Assume you want to make a field accept only numbers. Which attribute do you use?", options: ["type='number'", "type='text'", "pattern='[0-9]'", "inputmode='numeric'"], answer: 0 },
  { question: "Let's say you want to add a description to a <figure> element. Which tag do you use?", options: ["<figcaption>", "<caption>", "<desc>", "<summary>"], answer: 0 },
];
